### ISSUE TITLE
Broken with ACF version 5.6.0

### ISSUE THREAD

**Issue by bhuisman1992** [andersthorborg/ACF-Image-Crop#45]
Hi there,

With the new update of ACF the plugin doesn't work anymore!

Below are the errors:

Warning: json_decode() expects parameter 1 to be string, array given in /srv/www/perfettivanmelle/htdocs/wp-content/plugins/acf-image-crop-add-on/acf-image-crop-v5.php on line 946

Notice: Undefined index: save_format in /srv/www/perfettivanmelle/htdocs/wp-content/plugins/acf-image-crop-add-on/acf-image-crop-v5.php on line 959

Notice: Undefined index: save_format in /srv/www/perfettivanmelle/htdocs/wp-content/plugins/acf-image-crop-add-on/acf-image-crop-v5.php on line 973

Can you fix this?

**Comment by Jotswana** [comment]
First of all. Thank you for the Plufgin. We encountered the same Problem here. 
The entered fields don't exist anymore after the update of ACF. Neither in ACF (we use the Pro Version) nor in the frontend. An update on this would be great.

**Comment by kyuumeitai** [comment]
Hi all. 
I've made a test, printing the $field in the format_value function (line 939)

Interestingly enough, with ACF 5.5.14 it prints only the $field with the `[type] => image_crop` 

In 5.6.0. prints all the `[type] => image`, this is why there's so many warnings for missing properties.

I'll keep looking.

**Comment by kubajjz** [comment]
Thanks for this great plugin and please fix it...

**Comment by fhfournier** [comment]
Yes thanks for this plugin! I really need this update :-)

**Comment by gummiforweb** [comment]
Hi, 
The reason why 5.6 prints all [type] => image is because they way a custom field registered is different.
here's some info, hope it helps.  https://support.advancedcustomfields.com/forums/topic/acf-pro-5-6-update-restructured-plugin-files/

**Comment by joachimguido** [comment]
@gummiforweb I tried the method you explained in the blogpost on the ACF forum and it works!
I made the following changes in the acf-image-crop-v5.php file:
Changed:
`function __construct()`
to:
` public function initialize()`

and at the bottom of the function I deleted:
`  // do not delete!
        acf_field::__construct();
        //parent::__construct();`

WARNING: after making these changes, the plugin will no longer work on previous versions of ACF, so it's just for those who need it now for ACF 5.6 and up

**Comment by fhfournier** [comment]
Thanks @joachimguido!!!! Minor change and work great until the update !

**Comment by wearehyphen** [comment]
Thanks @joachimguido — worked a treat! Saves having to downgrade and lose features until the plugin is formally updated 👍

**Comment by elliotcondon** [comment]
Hi guys,

Elliot here from ACF. My apologies for the recent issue triggered in 5.6.0
My intention was never to harm 3rd party field types, in fact, it was the complete opposite. 

I discovered that due to the previous setup, it was not possible to ''extend' core ACF field types using the standard `parent::__construct();` method.

I did not realize that some 3rd party field types were calling the `acf_field::__construct();` directly as a work around - great thinking from the devs.

I believe that all is needed is to add an empty `initialize` function to the field class. Eg. Add this to the acf-image-crop-v5.php file:
```
	function initialize() {
		
		/* do nothing */
			
	}
```

This should prevent the core class over-writing the child class.
Please let me know if this solves the issue, and I will be sure to contact everyone involved.

Cheers
Elliot

**Comment by andersthorborg** [comment]
Hi guys,

The issue should be resolved by https://github.com/andersthorborg/ACF-Image-Crop/commit/cd3f55a2507626453a7f5609c0e991dc2c2842cc.

Thanks for taking action and thanks @elliotcondon for taking time to deal with 3rd party compatibility.

**Comment by garyconstable** [comment]
Hello, This has not fixed the issue for me, any ideas on what to do?

**Comment by cdeVision** [comment]
maybe your caching the old plugin files? Try clearing cache.

**Comment by garyconstable** [comment]
I cleared the cache using W3 Total Cache plugin - there was no change are there some files that I can manually delete ? 

thanks.

**Comment by cdeVision** [comment]
I thought it might have been your browser caching files.
